### ISSUE TITLE
Link broken in README.rst

### ISSUE THREAD

**Issue by IshwarBhat** [cordmata/mediaampy#1]
Current: MediaAmp/MPX [endpoints](http://help.theplatform.com/display/trc/Alphabetical+list+of+endpoints)

Fix: MediaAmp/MPX [endpoints](https://docs.theplatform.com/help/alphabetical-list-of-endpoints)

**Comment by cordmata** [comment]
Thanks Ishwar! Updated in commit https://github.com/cordmata/mediaampy/commit/442eb221f9cb67b71964dbfcee3c7999206f80f0

I no longer work for the organization where I had access to this content -- it's behind authentication so I'll trust it points to the right page!
